### ISSUE TITLE
Make a bump button (to bump papers to next meeting)

### ISSUE THREAD

**Issue by deskinsjt** [cwru-pat/coffee_voting_system#10]
Ties in with #8 and #9.
- I like the modal.
- Bump Looks ugly with paper buttons so staying with rating.
-  Make these tab-able

**Comment by deskinsjt** [comment]
Hmmm bump times aren't behaving; _get_adjacent meeting_times()_ maybe not handling minutes?

**Comment by jbmertens** [comment]
It handles minutes, but not seconds.
https://github.com/cwru-pat/coffee_stuff/blob/master/private/functions.php#L169
