### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by jbmertens** [cwru-pat/coffee_voting_system#12]
We could do something ourselves, BUT... it turns out arxiv has an API for searching:
http://arxiv.org/help/api/index
and will return results as xml:
http://export.arxiv.org/api/query?start=0&max_results=10&search_query=something

It would be neat if we could pull results in, particularly ones not currently stored, for voting purposes.

**Comment by jbmertens** [comment]
Mostly addressed by a3c064c and 4f4dc87.

Improvements can still be made.

**Comment by deskinsjt** [comment]
Paper titles aren't taking care of dupes well enough. Perhaps check dupes on (needs to be created) arXiv id column? May allow for post page to be less of a lie also.

**Comment by jbmertens** [comment]
Fixed for importing, but the field isn't used anywhere else.
