### ISSUE TITLE
Add "other" section to the main page

### ISSUE THREAD

**Issue by jbmertens** [cwru-pat/coffee_voting_system#20]
For papers that aren't in a section in .conf.php (cross-lists and imports can be).

Alternatively, do something like this:
https://github.com/cwru-pat/coffee_stuff/commit/47a5db9ce7290d7fab80dc95c573cd16ca04551d#commitcomment-11437837

**Comment by deskinsjt** [comment]
Why not put any papers that don't have a home into "users" and perhaps change that name to "other"? @jbcm627

**Comment by jbmertens** [comment]
That would work.
