### ISSUE TITLE
Failed import from arxiv search

### ISSUE THREAD

**Issue by cjcopi** [cwru-pat/coffee_voting_system#25]
Using the search to find paper 1507.03414 correctly finds it and offers the option to import it.  Clicking on "import" produces "import failed".  I did not try any other paper.  

I have not looked at the code at all but 
- the paper was submitted July 13 (yesterday) so should show up in the list tomorrow July 15, I guess?  It **is** on the arxiv and searchable but perhaps this causes an issue,
- this paper has TeX (math) in the title which could distinguish it from other papers

Yes I was logged in at the time.  Yes this happens on both chrome and firefox.

**Comment by jbmertens** [comment]
I see this error in the console when I attempt to import:

> GET `http://glamdring.case.edu/coffee/js/import.php?import-id=http%3A%2F%2Farxiv…aving+spin+3%2F2+and+the+other+5%2F2.+&section=hep-ex&arxivId=1507.03414v1` 414 (Request-URI Too Long)

...the full GET URL is really long (mostly due to a lot of authors on the paper) so this is hitting a URL length restriction on the server. Changing to POST request might be a workaround.
