### ISSUE TITLE
Display papers from a date range

### ISSUE THREAD

**Issue by jbmertens** [cwru-pat/coffee_voting_system#30]
rather than a single day.  @gstarkman suggests making papers from the previous meeting to next visible as default.

**Comment by jbmertens** [comment]
A couple minor issues with this:
- [x] The date overflows the input (using a smaller font might be the easiest fix)
- [x] The dates votes are shown from do not correspond to the selected date range.

![date_issues](https://cloud.githubusercontent.com/assets/964048/11462360/0d6eef80-96e1-11e5-90ff-3289329a9e9e.PNG)

**Comment by deskinsjt** [comment]
Concerning the first yes it does overflow the input. It is worse than your image makes it out as it depends on the screen size and it wasn't easy to make it do what I want. Haven't figured out a screen independent way to display useful information.

The second I think is the intended behavior. It is showing the papers from the meeting associated with the end date as I think it should.
