### ISSUE TITLE
Unable to view entire sidebar on browsers with low vertical height

### ISSUE THREAD

**Issue by jbmertens** [cwru-pat/coffee_voting_system#41]
See attached image.

The menu items can be accessed if I scroll all the way to the bottom of the page, but otherwise cannot.

![no_vscroll](https://cloud.githubusercontent.com/assets/964048/19688679/adcf599a-9a98-11e6-862a-7af4c8b5aa41.png)

**Comment by deskinsjt** [comment]
You should be able to go to the bottom of the menu once you scroll to the bottom of the page. This is working as intended. However I agree that making it a scrolling element would be good.

**Comment by jbmertens** [comment]
Yeah, I was thinking that the behavior (that it will appear at the bottom) isn't that intuitive because it takes so much scrolling.

> I agree that making it a scrolling element would be good.

Adding a scrollbar or something? Hm...

**Comment by deskinsjt** [comment]
I think we want ".pre-scrollable" but I know I had some trouble with that when we made the website.
