### ISSUE TITLE
Minor change to search/import

### ISSUE THREAD

**Issue by deskinsjt** [cwru-pat/coffee_voting_system#50]
It seems it is confusing for users to hit the `import paper` button and then the `view paper` button when using the search functionality. A minor change could alleviate this by making the `import paper` button both import and on success reroute to the post page. Thoughts?

**Comment by jbmertens** [comment]
Sounds like a good idea.

I always thought an internal search would be a good idea too, but that
seemed like a lot of work.

**Comment by deskinsjt** [comment]
After discussion with @modw  I think I will instead try to add vote buttons after import in the search modal.

Yeah internal search is a feature we will push to v2 of the website.

**Comment by deskinsjt** [comment]
Closed by de8ef894ecf87f3aff7a2b5bae9bbaae1554a57b.
